# Generated by Django 3.0.4 on 2020-03-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes_temporarias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adocao_temporaria',
            options={'verbose_name': 'adoção temporária', 'verbose_name_plural': 'adoções temporárias'},
        ),
    ]
