# Generated by Django 3.0.4 on 2020-03-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes_temporarias', '0002_auto_20200312_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adocao_temporaria',
            name='idade',
        ),
        migrations.AddField(
            model_name='adocao_temporaria',
            name='pet_especial',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adocao_temporaria',
            name='porte_desejado',
            field=models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1),
        ),
    ]
