# Generated by Django 3.0.4 on 2020-03-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('porte_desejado', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('I', 'Indiferente')], max_length=1)),
                ('pet_especial', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
            ],
            options={
                'verbose_name': 'Lar',
                'verbose_name_plural': 'Lares',
            },
        ),
    ]
