# Generated by Django 3.0.4 on 2020-03-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lares', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lar',
            options={'ordering': ['nome'], 'verbose_name': 'Lar', 'verbose_name_plural': 'Lares'},
        ),
    ]
