# Generated by Django 3.0.4 on 2020-03-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0002_auto_20200309_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ong',
            options={'verbose_name': 'ong', 'verbose_name_plural': 'ongs'},
        ),
    ]
