# Generated by Django 3.0.4 on 2020-03-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0003_auto_20200312_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ong',
            options={'ordering': ['nome'], 'verbose_name': 'ong', 'verbose_name_plural': 'ongs'},
        ),
    ]
