# Generated by Django 3.0.4 on 2020-03-12 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ongs', '0003_auto_20200312_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('cidade', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('descricao', models.TextField(max_length=500)),
                ('porte_desejado', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1)),
                ('pet_especial', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=1)),
                ('ong', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ongs.Ong')),
            ],
            options={
                'verbose_name': 'adoção temporária',
                'verbose_name_plural': 'adoções temporárias',
            },
        ),
    ]
