# Generated by Django 3.0.4 on 2020-03-15 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ongs', '0004_auto_20200315_1655'),
        ('pets', '0002_auto_20200315_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='ong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ong', to='ongs.Ong'),
        ),
    ]
